services:
  web:
    container_name: next_node_jwt_frontend
    build: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.local

    environment:
      NEXT_PUBLIC_API_URL: http://api:8000/api

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

    depends_on:
      - api

  api:
    container_name: next_node_jwt_backend
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

    environment:
      POSTGRES_HOST: db

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

    depends_on:
      - db

  db:
    container_name: next_node_jwt_db
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: next_node_jwt_volume
